# @package _global_

defaults:
  - /benchmark/rearrange: pick
  - /habitat_baselines: habitat_baselines_spa_config_base
  - _self_

habitat_baselines:
  video_dir: "data/vids/"

  sense_plan_act:
    verbose: True
    run_freq: 2
    n_grasps: 100
    mp_obj: True
    mp_margin: null
    mp_render: True
    timeout: 3
    exec_ee_thresh: 0.1
    # "Priv" or "Reg"
    mp_sim_type: "Priv"
    video_dir: 'data/vids'
    debug_dir: "data/mp_test"
    count_obj_collisions: True
    grasp_gen_is_verbose: True
    ik_dist_thresh: 0.1

  eval:
    video_option: ["disk"]

habitat:
  gym:
    obs_keys: ['joint', 'ee_pos']
    desired_goal_keys: ['obj_goal_pos_sensor']
    achieved_goal_keys: []
    action_keys: ['arm_action']
  task:
    success_reward: 2000.0
    end_on_success: False
