# @package _global_

defaults:

  - /habitat: habitat_config_base
  - /habitat/task: instance_imagenav
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgbds_agent
  # - /habitat/simulator/sensor_setups@habitat.simulator.agents.main_agent: rgbds_agent
  - /habitat/dataset/instance_imagenav: hm3d_v3
  - _self_


habitat:

  environment:
    max_episode_seconds: 1000
  simulator:
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 640
            height: 480
            hfov: 79
            position: [0, 1.31, 0]
          depth_sensor:
            width: 640
            height: 480
            hfov: 79
            min_depth: 0.5
            max_depth: 10.0
            position: [0, 1.31, 0]
          semantic_sensor:
            width: 640
            height: 480
            hfov: 79
            position: [0, 1.31, 0]
        height: 1.31
        radius: 0.10
        # max_climb: 0.2
    habitat_sim_v0:
      gpu_device_id: 0
      allow_sliding: True
  dataset:
    split: train

